export const STRINGS = {
  app: {
    name: "Biblioteca do Condomínio",
    tagline: "Your community's shared knowledge.",
    footer: "© 2025 Biblioteca do Condomínio. All rights reserved.",
  },
  nav: {
    home: "Home",
    lookup: "Reader Lookup",
    catalog: "Catalog",
    readerLogin: "Reader Portal",
    adminLogin: "Admin Portal",
  },
  common: {
    loading: "Loading...",
    noResults: "No results found.",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    details: "Details",
    search: "Search...",
    active: "Active",
    inactive: "Inactive",
  },
  lookup: {
    title: "Check Your Status",
    subtitle: "Enter your email to quickly check your active loans and reservations without logging in.",
    placeholder: "Enter your registered email...",
    buttonLabel: "Lookup",
    notFound: "No reader found with this email, or an error occurred.",
    readerFound: "Reader Found",
    activeLoans: "Active Loans",
    reservations: "Reservations",
    noLoans: "No active loans.",
    noReservations: "No active reservations.",
  },
  catalog: {
    searchPlaceholder: "Search titles, authors...",
    allGenres: "All Genres",
    reserve: "Reserve",
    queuePosition: "Queue position",
    availableNote: "Available — ask admin to borrow",
    unavailable: "Unavailable",
    noBooks: "No books found matching your search.",
  },
  reports: {
    title: "Returns & Reports",
    exportCsv: "Export CSV",
    filters: "Filters",
    statusFilter: "Status",
    readerFilter: "Reader",
    bookFilter: "Book",
    dateRange: "Date Range",
    allStatuses: "All Statuses",
    noRecords: "No records match the selected filters.",
    generating: "Generating report...",
  },
  readers: {
    title: "Manage Readers",
    registerNew: "Register New Reader",
    loadingReaders: "Loading readers...",
    noReaders: "No readers found.",
    fullName: "Full Name",
    emailAddress: "Email Address",
    block: "Block/Building",
    house: "Apt/House #",
    registerButton: "Register Reader",
  },
  loans: {
    title: "Manage Loans",
    newLoan: "New Loan",
    allLoans: "All Active Loans",
    overdue: "Overdue",
    dueSoon: "Due in 3 Days",
    loadingLoans: "Loading loans...",
    noLoans: "No loans found for this filter.",
    returnButton: "Return",
  },
  reservations: {
    title: "Reservation Queue",
    tabActive: "Active",
    tabExpired: "Expired",
    tabWaiting: "Waiting",
    tabHistory: "History",
    notifyWhatsApp: "Notify via WhatsApp",
    markPickedUp: "Mark Picked Up",
    advance: "Advance",
    noReservations: "No reservations in this category.",
  },
  books: {
    title: "Manage Books",
    addNew: "Add New Book",
    loadingBooks: "Loading books...",
    noBooks: "No books found.",
    aiSearch: "AI Search",
    saveBook: "Save Book",
    editBook: "Edit Book",
    newBook: "New Book",
  },
  readerDashboard: {
    activeLoans: "Active Loans",
    overdue: "Overdue",
    reservations: "Reservations",
    totalHistory: "Total History",
    ctaTitle: "Ready for a new adventure?",
    ctaSubtitle: "Browse our catalog to find your next great read. Reserve books currently out on loan to hold your place in line.",
    ctaButton: "Explore Catalog",
  },
  readerDetail: {
    backToReaders: "Back to Readers",
    deleteReader: "Delete Reader",
    deleteConfirm: "Are you sure you want to delete this reader? This action cannot be undone.",
    deleteSuccess: "Reader deleted",
    deleteFailed: "Failed to delete reader",
    statusUpdated: "Status updated",
    statusUpdateFailed: "Failed to update status",
    statusChangedTo: "Reader status changed to",
    notFound: "Reader not found.",
    memberSince: "Member since",
    accountStatus: "Account Status",
    activeLoans: "Active Loans",
    loanHistory: "Loan History",
    noActiveLoans: "No active loans.",
    noLoanHistory: "No loan history.",
    viewProfile: "View Reader Profile",
    statusPending: "Pending",
    statusBlocked: "Blocked",
    block: "Block",
    house: "House",
  },
  loanDetail: {
    backToLoans: "Back to Loans",
    loanNumber: "Loan #",
    markReturned: "Mark as Returned",
    returnConfirm: "Mark this loan as returned?",
    returnSuccess: "Loan marked as returned",
    returnFailed: "Failed to mark as returned",
    notFound: "Loan not found.",
    bookInfo: "Book Information",
    readerInfo: "Reader Information",
    loanDetails: "Loan Details",
    loanDate: "Loan Date",
    dueDate: "Due Date",
    returnDate: "Return Date",
    notReturned: "Not returned",
    overdueWarning: "This loan is overdue. Due date was",
    blockLabel: "Block",
    houseLabel: "House",
  },
  reservationsAdmin: {
    title: "Reservation Queue",
    tabActive: "Active",
    tabExpired: "Expired",
    tabWaiting: "Waiting",
    tabHistory: "History",
    positionLabel: "Position",
    notifyWhatsApp: "Notify via WhatsApp",
    markPickedUp: "Mark Picked Up",
    advance: "Advance",
    cancel: "Cancel",
    noReservations: "No reservations in this category.",
    actionSuccess: "Action successful",
    actionFailed: "Failed",
    readerLabel: "Reader:",
    whatsAppMsg: (name: string, bookTitle: string) =>
      `Hello ${name}, your reservation for "${bookTitle}" is ready! Please pick it up within 3 days.`,
  },
  home: {
    heroTitle: "Discover Your Next Great Read",
    heroSubtitle: "Explore a curated collection of books shared by your neighbors. Borrow, reserve, and manage your reading journey right from home.",
    stats: {
      books: "Total Books",
      available: "Available Now",
      readers: "Active Readers",
      loans: "Active Loans",
    },
    popular: "Popular Titles",
    announcements: "Library Announcements",
  },
  reader: {
    loginTitle: "Welcome Back, Reader",
    dashboard: "My Library",
    catalog: "Book Catalog",
    loans: "My Loans",
    reservations: "My Reservations",
    profile: "Profile Settings",
    logout: "Sign Out",
  },
  admin: {
    loginTitle: "Library Administration",
    dashboard: "Dashboard",
    books: "Manage Books",
    readers: "Manage Readers",
    loans: "Manage Loans",
    reservations: "Reservation Queue",
    reports: "Reports & Analytics",
    notes: "Library Notes",
    admins: "Administrators",
    logout: "Sign Out",
  },
  status: {
    book: {
      available: "Available",
      borrowed: "Borrowed",
      reserved: "Reserved",
      draft: "Draft",
      lost: "Lost",
      unavailable: "Unavailable",
    },
    loan: {
      active: "Active",
      returned: "Returned",
      overdue: "Overdue",
    },
    reservation: {
      waiting: "Waiting",
      notified: "Ready for Pickup",
      fulfilled: "Fulfilled",
      cancelled: "Cancelled",
    },
    user: {
      active: "Active",
      pending: "Pending",
      inactive: "Inactive",
      blocked: "Blocked",
    }
  }
};
